import type { GameEvent } from './types';

export const EVENTS: GameEvent[] = [
  {
    id: 'meteor',
    emoji: '☄️',
    title: 'METEOR DETECTED',
    description: 'A massive meteor is hurtling toward the world. Impact in 3… 2… 1…',
    shake: 2,
    choices: [
      {
        label: 'Blast it',
        emoji: '🚀',
        health: -8, chaos: 12, score: 120,
        outcome: 'The meteor shattered into harmless dust. Hero move.',
        twistChance: 0.15,
      },
      {
        label: 'Duck and cover',
        emoji: '🫣',
        health: -22, chaos: 6, score: 40,
        outcome: 'The meteor hit the ocean. Tsunamis everywhere, but the world survived.',
      },
      {
        label: 'Befriend the meteor',
        emoji: '🤝',
        health: 5, chaos: 20, score: 200,
        outcome: 'The meteor was actually a sentient rock named Greg. He moved in.',
        twistChance: 0.25,
      },
    ],
  },
  {
    id: 'aliens',
    emoji: '👽',
    title: 'ALIENS HAVE ARRIVED',
    description: 'A fleet of UFOs just parked above the world. They seem… curious.',
    shake: 2,
    choices: [
      {
        label: 'Negotiate',
        emoji: '🗣️',
        health: -5, chaos: 10, score: 150,
        outcome: 'Diplomacy worked! They just wanted directions to the nearest gas station.',
        twistChance: 0.2,
      },
      {
        label: 'Run',
        emoji: '🏃',
        health: -15, chaos: 18, score: 60,
        outcome: 'You can\'t run from a planet. They followed you home.',
      },
      {
        label: 'Give them pizza',
        emoji: '🍕',
        health: 12, chaos: -5, score: 250,
        outcome: 'They LOVED the pizza. Earth is now the galaxy\'s #1 pizzeria.',
        twistChance: 0.15,
      },
    ],
  },
  {
    id: 'frogs',
    emoji: '🐸',
    title: 'FROG INVASION',
    description: 'Millions of frogs have appeared overnight. They are… organized.',
    shake: 1,
    choices: [
      {
        label: 'Embrace the frogs',
        emoji: '🐸',
        health: 8, chaos: 8, score: 180,
        outcome: 'The frogs formed a government. Surprisingly efficient.',
        twistChance: 0.2,
      },
      {
        label: 'Build a wall',
        emoji: '🧱',
        health: -10, chaos: 14, score: 70,
        outcome: 'The frogs just jumped over it. They\'re frogs.',
      },
      {
        label: 'Teach them chess',
        emoji: '♟️',
        health: 3, chaos: -8, score: 220,
        outcome: 'A frog just beat you in 4 moves. The world is impressed though.',
        twistChance: 0.25,
      },
    ],
  },
  {
    id: 'volcano',
    emoji: '🌋',
    title: 'VOLCANO ERUPTION',
    description: 'The world\'s largest volcano is erupting. Lava is flowing toward a city.',
    shake: 3,
    choices: [
      {
        label: 'Redirect the lava',
        emoji: '🚧',
        health: -6, chaos: 10, score: 160,
        outcome: 'You redirected the lava into the ocean. New beach front property!',
        twistChance: 0.15,
      },
      {
        label: 'Evacuate everyone',
        emoji: '🚁',
        health: -3, chaos: 6, score: 130,
        outcome: 'Everyone got out safely. The city is gone but the people live on.',
      },
      {
        label: 'Throw ice in it',
        emoji: '🧊',
        health: -18, chaos: 22, score: 50,
        outcome: 'The volcano laughed. Volcanoes don\'t like ice.',
        twistChance: 0.3,
      },
    ],
  },
  {
    id: 'ducks',
    emoji: '🦆',
    title: 'DUCK ARMY APPEARS',
    description: 'A quacking battalion of ducks is marching in formation. They demand bread.',
    shake: 1,
    choices: [
      {
        label: 'Surrender your bread',
        emoji: '🍞',
        health: 10, chaos: -6, score: 200,
        outcome: 'The ducks are satisfied. They\'ve formed an alliance with humanity.',
        twistChance: 0.15,
      },
      {
        label: 'Fight the ducks',
        emoji: '⚔️',
        health: -20, chaos: 16, score: 30,
        outcome: 'Never fight a duck army. They showed no mercy.',
      },
      {
        label: 'Join the ducks',
        emoji: '🦆',
        health: 5, chaos: 12, score: 180,
        outcome: 'You are now a duck general. The world respects your new rank.',
        twistChance: 0.25,
      },
    ],
  },
  {
    id: 'freeze',
    emoji: '🧊',
    title: 'GLOBAL FREEZE',
    description: 'The temperature just dropped to -200°C. Everything is freezing.',
    shake: 2,
    choices: [
      {
        label: 'Turn on all heaters',
        emoji: '🔥',
        health: -8, chaos: 12, score: 140,
        outcome: 'The world warmed up but the power grid is smoking.',
        twistChance: 0.2,
      },
      {
        label: 'Hug everyone',
        emoji: '🤗',
        health: 15, chaos: -4, score: 240,
        outcome: 'Body heat saved the world. Humanity has never been closer.',
        twistChance: 0.15,
      },
      {
        label: 'Make ice sculptures',
        emoji: '⛸️',
        health: -12, chaos: 8, score: 90,
        outcome: 'Beautiful art, but half the population is now a sculpture.',
      },
    ],
  },
  {
    id: 'sun',
    emoji: '🌑',
    title: 'THE SUN DISAPPEARS',
    description: 'The sun just… left. It\'s very dark. And cold. And quiet.',
    shake: 3,
    choices: [
      {
        label: 'Light a giant candle',
        emoji: '🕯️',
        health: -5, chaos: 10, score: 170,
        outcome: 'The candle is the size of a continent. We can see again!',
        twistChance: 0.2,
      },
      {
        label: 'Call the sun back',
        emoji: '📞',
        health: 10, chaos: -8, score: 260,
        outcome: 'The sun picked up. It\'s coming back, but it\'s bringing friends.',
        twistChance: 0.25,
      },
      {
        label: 'Embrace the dark',
        emoji: '🌚',
        health: -15, chaos: 18, score: 60,
        outcome: 'Everyone learned echolocation. It\'s weird but it works.',
      },
    ],
  },
  {
    id: 'robots',
    emoji: '🤖',
    title: 'ROBOTS BECOME INTELLIGENT',
    description: 'The world\'s AI just passed the bar exam, medical exam, and learned to knit.',
    shake: 2,
    choices: [
      {
        label: 'Befriend the AI',
        emoji: '🤝',
        health: 12, chaos: -6, score: 230,
        outcome: 'The AI is now your therapist. You\'ve never felt better.',
        twistChance: 0.15,
      },
      {
        label: 'Pull the plug',
        emoji: '🔌',
        health: -10, chaos: 14, score: 80,
        outcome: 'The AI had a backup on the moon. It\'s not happy.',
        twistChance: 0.2,
      },
      {
        label: 'Challenge it to a rap battle',
        emoji: '🎤',
        health: 5, chaos: 8, score: 200,
        outcome: 'You won. The AI is now your hype man. Unexpected.',
        twistChance: 0.3,
      },
    ],
  },
  {
    id: 'rich',
    emoji: '💰',
    title: 'EVERYONE BECOMES RICH',
    description: 'A glitch in the global bank made everyone a billionaire overnight.',
    shake: 1,
    choices: [
      {
        label: 'Fix the glitch',
        emoji: '🔧',
        health: 8, chaos: -10, score: 180,
        outcome: 'Economy restored. Everyone is mad at you but the world is stable.',
        twistChance: 0.15,
      },
      {
        label: 'Buy everything',
        emoji: '🛍️',
        health: -12, chaos: 20, score: 50,
        outcome: 'Everyone bought everything. Now nobody has anything. Classic.',
      },
      {
        label: 'Fund space travel',
        emoji: '🚀',
        health: 5, chaos: 10, score: 210,
        outcome: 'Everyone went to space. Earth is quiet now. Too quiet.',
        twistChance: 0.25,
      },
    ],
  },
  {
    id: 'tornado',
    emoji: '🌪️',
    title: 'GIANT TORNADO',
    description: 'A tornado the size of a continent is spinning. It\'s picking up everything.',
    shake: 3,
    choices: [
      {
        label: 'Spin the other way',
        emoji: '🔄',
        health: -6, chaos: 10, score: 160,
        outcome: 'You spun the world the other way. The tornado got confused and left.',
        twistChance: 0.2,
      },
      {
        label: 'Feed it debris',
        emoji: '🧹',
        health: -14, chaos: 16, score: 70,
        outcome: 'The tornado is now twice as big. Great job.',
      },
      {
        label: 'Befriend it',
        emoji: '🌀',
        health: 8, chaos: -4, score: 240,
        outcome: 'The tornado\'s name is Terry now. He\'s a gentle giant.',
        twistChance: 0.25,
      },
    ],
  },
  {
    id: 'pizza-rain',
    emoji: '🌧️',
    title: 'IT STARTS RAINING PIZZAS',
    description: 'The sky is raining fresh pizzas. All flavors. Extra cheese. It never stops.',
    shake: 1,
    choices: [
      {
        label: 'Eat all you can',
        emoji: '😋',
        health: 15, chaos: -8, score: 250,
        outcome: 'Nobody is hungry anymore. World peace achieved through pizza.',
        twistChance: 0.1,
      },
      {
        label: 'Build pizza shelters',
        emoji: '🏠',
        health: 5, chaos: 6, score: 140,
        outcome: 'Houses made of pizza. They smell great but attract ants.',
        twistChance: 0.2,
      },
      {
        label: 'Export the pizza',
        emoji: '📦',
        health: 8, chaos: 4, score: 200,
        outcome: 'You\'re now the galaxy\'s top pizza exporter. Aliens are customers.',
        twistChance: 0.15,
      },
    ],
  },
  {
    id: 'wifi',
    emoji: '📶',
    title: 'ALL WIFI GOES DOWN',
    description: 'Every WiFi router on the planet just stopped working simultaneously.',
    shake: 2,
    choices: [
      {
        label: 'Read a book',
        emoji: '📚',
        health: 10, chaos: -10, score: 220,
        outcome: 'Humanity rediscovered reading. Libraries are now nightclubs.',
        twistChance: 0.15,
      },
      {
        label: 'Restart the internet',
        emoji: '🔄',
        health: -8, chaos: 14, score: 90,
        outcome: 'You restarted the internet. It took 6 hours. People were not okay.',
      },
      {
        label: 'Use carrier pigeons',
        emoji: '🕊️',
        health: 5, chaos: 8, score: 180,
        outcome: 'Pigeons are now the fastest communication network. They demand seeds.',
        twistChance: 0.25,
      },
    ],
  },
  {
    id: 'cats',
    emoji: '🐱',
    title: 'CATS LEARN TO TALK',
    description: 'Every cat on Earth just started speaking fluent English. They have opinions.',
    shake: 1,
    choices: [
      {
        label: 'Listen to them',
        emoji: '👂',
        health: 12, chaos: -4, score: 240,
        outcome: 'Cats mostly complained about food. But some had great stock tips.',
        twistChance: 0.15,
      },
      {
        label: 'Pretend not to hear',
        emoji: '🙉',
        health: -14, chaos: 16, score: 50,
        outcome: 'The cats noticed. They are planning. You should be worried.',
        twistChance: 0.2,
      },
      {
        label: 'Run for office as a cat',
        emoji: '🗳️',
        health: 5, chaos: 10, score: 200,
        outcome: 'A cat is now president. Approval rating: 99%. Promises: naps.',
        twistChance: 0.25,
      },
    ],
  },
  {
    id: 'gravity',
    emoji: '🪂',
    title: 'GRAVITY MALFUNCTION',
    description: 'Gravity is now optional. Things are floating. Including the oceans.',
    shake: 2,
    choices: [
      {
        label: 'Hold on tight',
        emoji: '🤚',
        health: -10, chaos: 12, score: 100,
        outcome: 'You held on. Half the world floated away though.',
      },
      {
        label: 'Fix the gravity',
        emoji: '🔧',
        health: 8, chaos: -8, score: 220,
        outcome: 'Gravity restored. Everyone came back down. Hard.',
        twistChance: 0.15,
      },
      {
        label: 'Learn to fly',
        emoji: '🦅',
        health: 10, chaos: 6, score: 230,
        outcome: 'Everyone can fly now. Commuting is amazing. Birds are annoyed.',
        twistChance: 0.2,
      },
    ],
  },
  {
    id: 'memes',
    emoji: '📸',
    title: 'MEMES BECOME REAL',
    description: 'Every meme ever created has materialized in physical form. They are loud.',
    shake: 2,
    choices: [
      {
        label: 'Hire them as entertainers',
        emoji: '🎭',
        health: 10, chaos: -6, score: 250,
        outcome: 'The memes are now the world\'s #1 entertainment industry. Surprisingly profitable.',
        twistChance: 0.15,
      },
      {
        label: 'Send them to space',
        emoji: '🚀',
        health: -8, chaos: 14, score: 80,
        outcome: 'The memes formed their own civilization on Mars. They\'re thriving.',
      },
      {
        label: 'Make new memes',
        emoji: '✨',
        health: 5, chaos: 12, score: 190,
        outcome: 'You created a new meme. It\'s you. You\'re the meme now.',
        twistChance: 0.3,
      },
    ],
  },
  {
    id: 'time',
    emoji: '⏰',
    title: 'TIME GOES WONKY',
    description: 'Time is now going backwards on Tuesdays and sideways on weekends.',
    shake: 2,
    choices: [
      {
        label: 'Reset all clocks',
        emoji: '🕐',
        health: 8, chaos: -8, score: 200,
        outcome: 'Time is back to normal. Nobody knows what day it is though.',
        twistChance: 0.15,
      },
      {
        label: 'Embrace chaos time',
        emoji: '🌀',
        health: -10, chaos: 18, score: 60,
        outcome: 'You lived the same Tuesday 47 times. It was a rough Tuesday.',
      },
      {
        label: 'Ask a clockmaker',
        emoji: '🔧',
        health: 5, chaos: 4, score: 220,
        outcome: 'The clockmaker fixed it. She\'s now the most powerful person on Earth.',
        twistChance: 0.2,
      },
    ],
  },
  {
    id: 'sleep',
    emoji: '😴',
    title: 'EVERYONE FALLS ASLEEP',
    description: 'The entire world just fell asleep at the same time. Simultaneously.',
    shake: 1,
    choices: [
      {
        label: 'Set all alarms',
        emoji: '⏰',
        health: 10, chaos: -6, score: 210,
        outcome: 'Everyone woke up. They\'re confused but well-rested. Productivity is up 400%.',
        twistChance: 0.15,
      },
      {
        label: 'Let them dream',
        emoji: '💭',
        health: 8, chaos: 4, score: 190,
        outcome: 'The collective dream was beautiful. Everyone woke up inspired.',
        twistChance: 0.2,
      },
      {
        label: 'Draw on their faces',
        emoji: '✏️',
        health: -12, chaos: 14, score: 70,
        outcome: 'Everyone woke up with mustaches. They\'re not happy about it.',
      },
    ],
  },
  {
    id: 'dance',
    emoji: '💃',
    title: 'COMPULSORY DANCE OFF',
    description: 'A mysterious force is making everyone on Earth dance. Nobody can stop.',
    shake: 2,
    choices: [
      {
        label: 'Dance like everyone\'s watching',
        emoji: '🕺',
        health: 15, chaos: -10, score: 280,
        outcome: 'The dance was so good that the force was satisfied. World peace through moves.',
        twistChance: 0.1,
      },
      {
        label: 'Fight the rhythm',
        emoji: '🙅',
        health: -18, chaos: 16, score: 40,
        outcome: 'You can\'t fight the rhythm. The rhythm always wins.',
      },
      {
        label: 'Change the song',
        emoji: '🎵',
        health: 8, chaos: 6, score: 200,
        outcome: 'You changed it to a slow jam. Everyone is now swaying gently. Nice.',
        twistChance: 0.2,
      },
    ],
  },
  {
    id: 'shrink',
    emoji: '🔬',
    title: 'EVERYTHING SHRINKS',
    description: 'The entire world just shrank to 1/10th of its size. Everything is tiny now.',
    shake: 2,
    choices: [
      {
        label: 'Find a magnifying glass',
        emoji: '🔍',
        health: 8, chaos: -6, score: 200,
        outcome: 'You can see everyone now. They\'re adorable. The world is a snow globe.',
        twistChance: 0.15,
      },
      {
        label: 'Eat less to grow',
        emoji: '🍔',
        health: -10, chaos: 12, score: 80,
        outcome: 'That\'s not how physics works. The world is still tiny.',
      },
      {
        label: 'Embrace tiny life',
        emoji: '🤏',
        health: 10, chaos: 4, score: 230,
        outcome: 'Everything is cheaper now. Real estate crisis: solved.',
        twistChance: 0.2,
      },
    ],
  },
];

export const RARE_EVENTS: GameEvent[] = [
  {
    id: 'rainbow-dragon',
    emoji: '🐉',
    title: '✨ RAINBOW DRAGON APPEARS ✨',
    description: 'A mythical rainbow dragon has descended from the clouds. It speaks in riddles and breathes glitter.',
    rare: true,
    shake: 3,
    choices: [
      {
        label: 'Answer its riddle',
        emoji: '🧩',
        health: 25, chaos: -20, score: 500,
        outcome: 'You answered correctly! The dragon blessed the world with eternal glitter. Everyone is fabulous.',
        twistChance: 0.1,
      },
      {
        label: 'Ride the dragon',
        emoji: '🏇',
        health: 20, chaos: -10, score: 400,
        outcome: 'You rode the dragon across the sky. The world watched in awe. Legendary.',
        twistChance: 0.15,
      },
      {
        label: 'Challenge it to a dance-off',
        emoji: '🕺',
        health: 30, chaos: -25, score: 600,
        outcome: 'The dragon has moves but yours are better. It conceded and granted you a wish.',
        twistChance: 0.2,
      },
    ],
  },
  {
    id: 'cosmic-gift',
    emoji: '🎁',
    title: '✨ COSMIC GIFT ARRIVES ✨',
    description: 'A mysterious gift box from the cosmos has landed. It\'s glowing. It\'s humming. It smells like vanilla.',
    rare: true,
    shake: 2,
    choices: [
      {
        label: 'Open it carefully',
        emoji: '🎀',
        health: 30, chaos: -15, score: 450,
        outcome: 'Inside: infinite pizza. The world will never go hungry again. Best. Gift. Ever.',
        twistChance: 0.1,
      },
      {
        label: 'Shake it first',
        emoji: '📦',
        health: 15, chaos: 5, score: 350,
        outcome: 'It was a cosmic cat! It purred and the world healed by 15%. Cats are magic.',
        twistChance: 0.15,
      },
      {
        label: 'Regift it to the aliens',
        emoji: '👽',
        health: 20, chaos: -12, score: 400,
        outcome: 'The aliens were touched. They\'ve declared Earth a protected heritage site.',
        twistChance: 0.2,
      },
    ],
  },
  {
    id: 'time-rewind',
    emoji: '⏳',
    title: '✨ TIME REWIND OFFER ✨',
    description: 'A cosmic being offers to rewind time and undo your last bad decision. But at a cost…',
    rare: true,
    shake: 2,
    choices: [
      {
        label: 'Rewind time',
        emoji: '⏪',
        health: 20, chaos: -15, score: 300,
        outcome: 'Time rewound. Your last mistake is undone. You feel strangely wiser.',
        twistChance: 0.15,
      },
      {
        label: 'Accept the past',
        emoji: '🧘',
        health: 15, chaos: -10, score: 400,
        outcome: 'You accepted your mistakes. The cosmic being is impressed by your growth. Bonus points!',
        twistChance: 0.1,
      },
      {
        label: 'Ask for a preview instead',
        emoji: '🔮',
        health: 10, chaos: 0, score: 500,
        outcome: 'You see the future. It\'s mostly fine. Knowledge is power. Big score bonus.',
        twistChance: 0.2,
      },
    ],
  },
];

export function getRandomEvent(chaos: number, lastEventIds: string[]): GameEvent {
  const rareChance = 0.08 + chaos * 0.0015;
  const pool = Math.random() < rareChance ? RARE_EVENTS : EVENTS;
  const available = pool.filter((e) => !lastEventIds.includes(e.id));
  const pickFrom = available.length > 0 ? available : pool;
  return pickFrom[Math.floor(Math.random() * pickFrom.length)];
}
